name: '* Main'
run-name: 'Build and Test'
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'branch or tag to build'
        default: 'develop'
        type: string
jobs:
  run-unit:
    if: ${{ github.event.inputs.run_build == 'true' }}
    name: 'tests'
    uses: ./.github/workflows/run-tests.yaml
    secrets: inherit

  run-sonar:
    if: ${{ github.event.inputs.run_build == 'true' }}
    needs: [run-unit]
    uses: ./.github/workflows/run-sonar.yaml
    secrets: inherit

  build-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name }}
      - name: Build Artifact
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
      - run: npm install
      - run: npm run dist
